/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function cal(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function __wbg_heroattrsstatic_free(a: number): void;
export function __wbg_heroattrsrequired_free(a: number): void;
export function __wbg_get_heroattrsrequired_dmg(a: number): number;
export function __wbg_set_heroattrsrequired_dmg(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_max_hp(a: number): number;
export function __wbg_set_heroattrsrequired_max_hp(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_speed(a: number): number;
export function __wbg_set_heroattrsrequired_speed(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_crit_power(a: number): number;
export function __wbg_set_heroattrsrequired_crit_power(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_crit_rate(a: number): number;
export function __wbg_set_heroattrsrequired_crit_rate(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_defense(a: number): number;
export function __wbg_set_heroattrsrequired_defense(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_attack(a: number): number;
export function __wbg_set_heroattrsrequired_attack(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_effect_hit_rate(a: number): number;
export function __wbg_set_heroattrsrequired_effect_hit_rate(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_effect_resist_rate(a: number): number;
export function __wbg_set_heroattrsrequired_effect_resist_rate(a: number, b: number): void;
export function __wbg_get_heroattrsrequired_suit_4(a: number, b: number): void;
export function __wbg_set_heroattrsrequired_suit_4(a: number, b: number, c: number): void;
export function __wbg_get_heroattrsrequired_suit_2(a: number, b: number): void;
export function __wbg_set_heroattrsrequired_suit_2(a: number, b: number, c: number): void;
export function __wbg_get_heroattrsstatic_max_hp(a: number): number;
export function __wbg_get_heroattrsstatic_speed(a: number): number;
export function __wbg_get_heroattrsstatic_crit_power(a: number): number;
export function __wbg_get_heroattrsstatic_crit_rate(a: number): number;
export function __wbg_get_heroattrsstatic_defense(a: number): number;
export function __wbg_get_heroattrsstatic_attack(a: number): number;
export function __wbg_get_heroattrsstatic_effect_hit_rate(a: number): number;
export function __wbg_get_heroattrsstatic_effect_resist_rate(a: number): number;
export function __wbg_set_heroattrsstatic_max_hp(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_speed(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_crit_power(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_crit_rate(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_defense(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_attack(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_effect_hit_rate(a: number, b: number): void;
export function __wbg_set_heroattrsstatic_effect_resist_rate(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
